from ..base import _Enum, Market, Currency

# Limits
ORDERS_LIMIT = 100


class Currency(Currency):
    AAVE = dict(value="AAVE")
    ADA = dict(value="ADA")
    ALGO = dict(value="ALGO")
    ARS = dict(value="ARS")
    ATOM = dict(value="ATOM")
    AVAX = dict(value="AVAX")
    BCH = dict(value="BCH")
    BNB = dict(value="BNB")
    BRL = dict(value="BRL")
    BSV = dict(value="BSV")
    BTC = dict(value="BTC")
    BTTOLD = dict(value="BTTOLD")
    BUSD = dict(value="BUSD")
    CEL = dict(value="CEL")
    CLP = dict(value="CLP")
    COMP = dict(value="COMP")
    COP = dict(value="COP")
    CRO = dict(value="CRO")
    DAI = dict(value="DAI")
    DASH = dict(value="DASH")
    DOT = dict(value="DOT")
    ENJ = dict(value="ENJ")
    EOS = dict(value="EOS")
    ETH = dict(value="ETH", decimals=9)
    EURS = dict(value="EURS")
    FIL = dict(value="FIL")
    HT = dict(value="HT")
    LINK = dict(value="LINK")
    LTC = dict(value="LTC")
    LUNA = dict(value="LUNA")
    MATIC = dict(value="MATIC")
    MKR = dict(value="MKR")
    NEO = dict(value="NEO")
    NEXO = dict(value="NEXO")
    OMG = dict(value="OMG")
    ONE = dict(value="ONE")
    ONT = dict(value="ONT")
    PAXG = dict(value="PAXG")
    PEN = dict(value="PEN")
    RUNE = dict(value="RUNE")
    SHIB = dict(value="SHIB")
    SOL = dict(value="SOL")
    THETA = dict(value="THETA")
    TRX = dict(value="TRX")
    TUSD = dict(value="TUSD")
    UNI = dict(value="UNI")
    USDC = dict(value="USDC")
    USDP = dict(value="USDP")
    USDT = dict(value="USDT")
    USDT20 = dict(value="USDT20")
    USDTRX = dict(value="USDTRX")
    VET = dict(value="VET")
    XEM = dict(value="XEM")
    XLM = dict(value="XLM")
    XMR = dict(value="XMR")
    XRP = dict(value="XRP")
    XTZ = dict(value="XTZ")
    YFI = dict(value="YFI")
    ZEC = dict(value="ZEC")



class OrderType(_Enum):
    BUY = "buy"
    SELL = "sell"


class Market(Market):
    AAVE_BTC    = dict( value = "AAVEBTC" , base = Currency.AAVE   ,   quote =   Currency.BTC    )      
    AAVE_ETH    = dict( value = "AAVEETH" , base = Currency.AAVE   ,   quote =   Currency.ETH    )      
    AAVE_USDT   = dict( value = "AAVEUSDT" , base = Currency.AAVE   ,   quote =   Currency.USDT   )      
    ADA_BTC     = dict( value = "ADABTC" , base = Currency.ADA    ,   quote =   Currency.BTC    )      
    ADA_ETH     = dict( value = "ADAETH" , base = Currency.ADA    ,   quote =   Currency.ETH    )      
    ADA_USDT    = dict( value = "ADAUSDT" , base = Currency.ADA    ,   quote =   Currency.USDT   )      
    ALGO_BTC    = dict( value = "ALGOBTC" , base = Currency.ALGO   ,   quote =   Currency.BTC    )      
    ALGO_ETH    = dict( value = "ALGOETH" , base = Currency.ALGO   ,   quote =   Currency.ETH    )      
    ALGO_USDT   = dict( value = "ALGOUSDT" , base = Currency.ALGO   ,   quote =   Currency.USDT   )      
    ATOM_BTC    = dict( value = "ATOMBTC" , base = Currency.ATOM   ,   quote =   Currency.BTC    )      
    ATOM_ETH    = dict( value = "ATOMETH" , base = Currency.ATOM   ,   quote =   Currency.ETH    )      
    ATOM_USDT   = dict( value = "ATOMUSDT" , base = Currency.ATOM   ,   quote =   Currency.USDT   )      
    AVAX_BTC    = dict( value = "AVAXBTC" , base = Currency.AVAX   ,   quote =   Currency.BTC    )      
    AVAX_USDT   = dict( value = "AVAXUSDT" , base = Currency.AVAX   ,   quote =   Currency.USDT   )      
    BCH_BTC     = dict( value = "BCHBTC" , base = Currency.BCH    ,   quote =   Currency.BTC    )      
    BCH_ETH     = dict( value = "BCHETH" , base = Currency.BCH    ,   quote =   Currency.ETH    )      
    BCH_EURS    = dict( value = "BCHEURS" , base = Currency.BCH    ,   quote =   Currency.EURS   )      
    BCH_USDT    = dict( value = "BCHUSDT" , base = Currency.BCH    ,   quote =   Currency.USDT   )      
    BNB_BTC     = dict( value = "BNBBTC" , base = Currency.BNB    ,   quote =   Currency.BTC    )      
    BNB_ETH     = dict( value = "BNBETH" , base = Currency.BNB    ,   quote =   Currency.ETH    )      
    BNB_USDT    = dict( value = "BNBUSDT" , base = Currency.BNB    ,   quote =   Currency.USDT   )      
    BSV_BTC     = dict( value = "BSVBTC" , base = Currency.BSV    ,   quote =   Currency.BTC    )      
    BSV_USDT    = dict( value = "BSVUSDT" , base = Currency.BSV    ,   quote =   Currency.USDT   )      
    BTC_ARS     = dict( value = "BTCARS" , base = Currency.BTC    ,   quote =   Currency.ARS    )      
    BTC_BRL     = dict( value = "BTCBRL" , base = Currency.BTC    ,   quote =   Currency.BRL    )      
    BTC_BUSD    = dict( value = "BTCBUSD" , base = Currency.BTC    ,   quote =   Currency.BUSD   )      
    BTC_CLP     = dict( value = "BTCCLP" , base = Currency.BTC    ,   quote =   Currency.CLP    )      
    BTC_DAI     = dict( value = "BTCDAI" , base = Currency.BTC    ,   quote =   Currency.DAI    )      
    BTC_EURS    = dict( value = "BTCEURS" , base = Currency.BTC    ,   quote =   Currency.EURS   )      
    BTC_TUSD    = dict( value = "BTCTUSD" , base = Currency.BTC    ,   quote =   Currency.TUSD   )      
    BTC_USDC    = dict( value = "BTCUSDC" , base = Currency.BTC    ,   quote =   Currency.USDC   )      
    BTC_USDP    = dict( value = "BTCUSDP" , base = Currency.BTC    ,   quote =   Currency.USDP   )      
    BTC_USDT    = dict( value = "BTCUSDT" , base = Currency.BTC    ,   quote =   Currency.USDT   )      
    BTTOLD_BTC  = dict( value = "BTTOLDBTC" , base = Currency.BTTOLD ,   quote =   Currency.BTC    )      
    BTTOLD_ETH  = dict( value = "BTTOLDETH" , base = Currency.BTTOLD ,   quote =   Currency.ETH    )      
    BTTOLD_USDT = dict( value = "BTTOLDUSDT" , base = Currency.BTTOLD ,   quote =   Currency.USDT   )      
    CEL_BTC     = dict( value = "CELBTC" , base = Currency.CEL    ,   quote =   Currency.BTC    )      
    CEL_ETH     = dict( value = "CELETH" , base = Currency.CEL    ,   quote =   Currency.ETH    )      
    COMP_BTC    = dict( value = "COMPBTC" , base = Currency.COMP   ,   quote =   Currency.BTC    )      
    COMP_ETH    = dict( value = "COMPETH" , base = Currency.COMP   ,   quote =   Currency.ETH    )      
    COMP_USDT   = dict( value = "COMPUSDT" , base = Currency.COMP   ,   quote =   Currency.USDT   )      
    CRO_BTC     = dict( value = "CROBTC" , base = Currency.CRO    ,   quote =   Currency.BTC    )      
    CRO_ETH     = dict( value = "CROETH" , base = Currency.CRO    ,   quote =   Currency.ETH    )      
    CRO_USDT    = dict( value = "CROUSDT" , base = Currency.CRO    ,   quote =   Currency.USDT   )      
    DAI_USDC    = dict( value = "DAIUSDC" , base = Currency.DAI    ,   quote =   Currency.USDC   )      
    DASH_BTC    = dict( value = "DASHBTC" , base = Currency.DASH   ,   quote =   Currency.BTC    )      
    DASH_ETH    = dict( value = "DASHETH" , base = Currency.DASH   ,   quote =   Currency.ETH    )      
    DASH_EURS   = dict( value = "DASHEURS" , base = Currency.DASH   ,   quote =   Currency.EURS   )      
    DASH_USDT   = dict( value = "DASHUSDT" , base = Currency.DASH   ,   quote =   Currency.USDT   )      
    DOT_BTC     = dict( value = "DOTBTC" , base = Currency.DOT    ,   quote =   Currency.BTC    )      
    DOT_ETH     = dict( value = "DOTETH" , base = Currency.DOT    ,   quote =   Currency.ETH    )      
    DOT_USDT    = dict( value = "DOTUSDT" , base = Currency.DOT    ,   quote =   Currency.USDT   )      
    ENJ_BTC     = dict( value = "ENJBTC" , base = Currency.ENJ    ,   quote =   Currency.BTC    )      
    ENJ_ETH     = dict( value = "ENJETH" , base = Currency.ENJ    ,   quote =   Currency.ETH    )      
    ENJ_USDT    = dict( value = "ENJUSDT" , base = Currency.ENJ    ,   quote =   Currency.USDT   )      
    EOS_BTC     = dict( value = "EOSBTC" , base = Currency.EOS    ,   quote =   Currency.BTC    )      
    EOS_ETH     = dict( value = "EOSETH" , base = Currency.EOS    ,   quote =   Currency.ETH    )      
    EOS_EURS    = dict( value = "EOSEURS" , base = Currency.EOS    ,   quote =   Currency.EURS   )      
    EOS_USDT    = dict( value = "EOSUSDT" , base = Currency.EOS    ,   quote =   Currency.USDT   )      
    ETH_ARS     = dict( value = "ETHARS" , base = Currency.ETH    ,   quote =   Currency.ARS    )      
    ETH_BRL     = dict( value = "ETHBRL" , base = Currency.ETH    ,   quote =   Currency.BRL    )      
    ETH_BTC     = dict( value = "ETHBTC" , base = Currency.ETH    ,   quote =   Currency.BTC    )      
    ETH_CLP     = dict( value = "ETHCLP" , base = Currency.ETH    ,   quote =   Currency.CLP    )      
    ETH_DAI     = dict( value = "ETHDAI" , base = Currency.ETH    ,   quote =   Currency.DAI    )      
    ETH_EURS    = dict( value = "ETHEURS" , base = Currency.ETH    ,   quote =   Currency.EURS   )      
    ETH_TUSD    = dict( value = "ETHTUSD" , base = Currency.ETH    ,   quote =   Currency.TUSD   )      
    ETH_USDC    = dict( value = "ETHUSDC" , base = Currency.ETH    ,   quote =   Currency.USDC   )      
    ETH_USDP    = dict( value = "ETHUSDP" , base = Currency.ETH    ,   quote =   Currency.USDP   )      
    ETH_USDT    = dict( value = "ETHUSDT" , base = Currency.ETH    ,   quote =   Currency.USDT   )      
    EURS_DAI    = dict( value = "EURSDAI" , base = Currency.EURS   ,   quote =   Currency.DAI    )      
    EURS_TUSD   = dict( value = "EURSTUSD" , base = Currency.EURS   ,   quote =   Currency.TUSD   )      
    EURS_USDT   = dict( value = "EURSUSDT" , base = Currency.EURS   ,   quote =   Currency.USDT   )      
    FIL_BTC     = dict( value = "FILBTC" , base = Currency.FIL    ,   quote =   Currency.BTC    )      
    FIL_USDT    = dict( value = "FILUSDT" , base = Currency.FIL    ,   quote =   Currency.USDT   )      
    HT_BTC      = dict( value = "HTBTC" , base = Currency.HT ,   quote =   Currency.BTC    )      
    HT_USDT     = dict( value = "HTUSDT" , base = Currency.HT ,   quote =   Currency.USDT   )      
    LINK_BTC    = dict( value = "LINKBTC" , base = Currency.LINK   ,   quote =   Currency.BTC    )      
    LINK_ETH    = dict( value = "LINKETH" , base = Currency.LINK   ,   quote =   Currency.ETH    )      
    LINK_USDT   = dict( value = "LINKUSDT" , base = Currency.LINK   ,   quote =   Currency.USDT   )      
    LTC_BTC     = dict( value = "LTCBTC" , base = Currency.LTC    ,   quote =   Currency.BTC    )      
    LTC_ETH     = dict( value = "LTCETH" , base = Currency.LTC    ,   quote =   Currency.ETH    )      
    LTC_EURS    = dict( value = "LTCEURS" , base = Currency.LTC    ,   quote =   Currency.EURS   )      
    LTC_USDT    = dict( value = "LTCUSDT" , base = Currency.LTC    ,   quote =   Currency.USDT   )      
    LUNA_BTC    = dict( value = "LUNABTC" , base = Currency.LUNA   ,   quote =   Currency.BTC    )      
    LUNA_USDT   = dict( value = "LUNAUSDT" , base = Currency.LUNA   ,   quote =   Currency.USDT   )      
    MATIC_BTC   = dict( value = "MATICBTC" , base = Currency.MATIC  ,   quote =   Currency.BTC    )      
    MKR_BTC     = dict( value = "MKRBTC" , base = Currency.MKR    ,   quote =   Currency.BTC    )      
    MKR_DAI     = dict( value = "MKRDAI" , base = Currency.MKR    ,   quote =   Currency.DAI    )      
    MKR_ETH     = dict( value = "MKRETH" , base = Currency.MKR    ,   quote =   Currency.ETH    )      
    MKR_USDT    = dict( value = "MKRUSDT" , base = Currency.MKR    ,   quote =   Currency.USDT   )      
    NEO_BTC     = dict( value = "NEOBTC" , base = Currency.NEO    ,   quote =   Currency.BTC    )      
    NEO_ETH     = dict( value = "NEOETH" , base = Currency.NEO    ,   quote =   Currency.ETH    )      
    NEO_EURS    = dict( value = "NEOEURS" , base = Currency.NEO    ,   quote =   Currency.EURS   )      
    NEO_USDT    = dict( value = "NEOUSDT" , base = Currency.NEO    ,   quote =   Currency.USDT   )      
    NEXO_BTC    = dict( value = "NEXOBTC" , base = Currency.NEXO   ,   quote =   Currency.BTC    )      
    NEXO_ETH    = dict( value = "NEXOETH" , base = Currency.NEXO   ,   quote =   Currency.ETH    )      
    NEXO_USDT   = dict( value = "NEXOUSDT" , base = Currency.NEXO   ,   quote =   Currency.USDT   )      
    OMG_BTC     = dict( value = "OMGBTC" , base = Currency.OMG    ,   quote =   Currency.BTC    )      
    OMG_ETH     = dict( value = "OMGETH" , base = Currency.OMG    ,   quote =   Currency.ETH    )      
    OMG_USDT    = dict( value = "OMGUSDT" , base = Currency.OMG    ,   quote =   Currency.USDT   )      
    ONE_BTC     = dict( value = "ONEBTC" , base = Currency.ONE    ,   quote =   Currency.BTC    )      
    ONE_USDT    = dict( value = "ONEUSDT" , base = Currency.ONE    ,   quote =   Currency.USDT   )      
    ONT_BTC     = dict( value = "ONTBTC" , base = Currency.ONT    ,   quote =   Currency.BTC    )      
    ONT_ETH     = dict( value = "ONTETH" , base = Currency.ONT    ,   quote =   Currency.ETH    )      
    ONT_USDT    = dict( value = "ONTUSDT" , base = Currency.ONT    ,   quote =   Currency.USDT   )      
    PAXG_BTC    = dict( value = "PAXGBTC" , base = Currency.PAXG   ,   quote =   Currency.BTC    )      
    PAXG_USDT   = dict( value = "PAXGUSDT" , base = Currency.PAXG   ,   quote =   Currency.USDT   )      
    RUNE_BTC    = dict( value = "RUNEBTC" , base = Currency.RUNE   ,   quote =   Currency.BTC    )      
    RUNE_USDT   = dict( value = "RUNEUSDT" , base = Currency.RUNE   ,   quote =   Currency.USDT   )      
    SHIB_BTC    = dict( value = "SHIBBTC" , base = Currency.SHIB   ,   quote =   Currency.BTC    )      
    SHIB_USDT   = dict( value = "SHIBUSDT" , base = Currency.SHIB   ,   quote =   Currency.USDT   )      
    SOL_BTC     = dict( value = "SOLBTC" , base = Currency.SOL    ,   quote =   Currency.BTC    )      
    THETA_BTC   = dict( value = "THETABTC" , base = Currency.THETA  ,   quote =   Currency.BTC    )      
    THETA_USDT  = dict( value = "THETAUSDT" , base = Currency.THETA  ,   quote =   Currency.USDT   )      
    TRX_BTC     = dict( value = "TRXBTC" , base = Currency.TRX    ,   quote =   Currency.BTC    )      
    TRX_ETH     = dict( value = "TRXETH" , base = Currency.TRX    ,   quote =   Currency.ETH    )      
    TRX_USDT    = dict( value = "TRXUSDT" , base = Currency.TRX    ,   quote =   Currency.USDT   )      
    TUSD_DAI    = dict( value = "TUSDDAI" , base = Currency.TUSD   ,   quote =   Currency.DAI    )      
    TUSD_USDC   = dict( value = "TUSDUSDC" , base = Currency.TUSD   ,   quote =   Currency.USDC   )      
    UNI_BTC     = dict( value = "UNIBTC" , base = Currency.UNI    ,   quote =   Currency.BTC    )      
    UNI_USDT    = dict( value = "UNIUSDT" , base = Currency.UNI    ,   quote =   Currency.USDT   )      
    USDT_DAI    = dict( value = "USDTDAI" , base = Currency.USDT   ,   quote =   Currency.DAI    )      
    USDT_TUSD   = dict( value = "USDTTUSD" , base = Currency.USDT   ,   quote =   Currency.TUSD   )      
    USDT_USDC   = dict( value = "USDTUSDC" , base = Currency.USDT   ,   quote =   Currency.USDC   )      
    USDT_USDP   = dict( value = "USDTUSDP" , base = Currency.USDT   ,   quote =   Currency.USDP   )      
    VET_BTC     = dict( value = "VETBTC" , base = Currency.VET    ,   quote =   Currency.BTC    )      
    VET_ETH     = dict( value = "VETETH" , base = Currency.VET    ,   quote =   Currency.ETH    )      
    VET_USDT    = dict( value = "VETUSDT" , base = Currency.VET    ,   quote =   Currency.USDT   )      
    XEM_BTC     = dict( value = "XEMBTC" , base = Currency.XEM    ,   quote =   Currency.BTC    )      
    XEM_ETH     = dict( value = "XEMETH" , base = Currency.XEM    ,   quote =   Currency.ETH    )      
    XEM_USDT    = dict( value = "XEMUSDT" , base = Currency.XEM    ,   quote =   Currency.USDT   )      
    XLM_BTC     = dict( value = "XLMBTC" , base = Currency.XLM    ,   quote =   Currency.BTC    )      
    XLM_ETH     = dict( value = "XLMETH" , base = Currency.XLM    ,   quote =   Currency.ETH    )      
    XLM_USDT    = dict( value = "XLMUSDT" , base = Currency.XLM    ,   quote =   Currency.USDT   )      
    XMR_BTC     = dict( value = "XMRBTC" , base = Currency.XMR    ,   quote =   Currency.BTC    )      
    XMR_ETH     = dict( value = "XMRETH" , base = Currency.XMR    ,   quote =   Currency.ETH    )      
    XMR_EURS    = dict( value = "XMREURS" , base = Currency.XMR    ,   quote =   Currency.EURS   )      
    XMR_USDT    = dict( value = "XMRUSDT" , base = Currency.XMR    ,   quote =   Currency.USDT   )      
    XRP_BTC     = dict( value = "XRPBTC" , base = Currency.XRP    ,   quote =   Currency.BTC    )      
    XRP_ETH     = dict( value = "XRPETH" , base = Currency.XRP    ,   quote =   Currency.ETH    )      
    XRP_EURS    = dict( value = "XRPEURS" , base = Currency.XRP    ,   quote =   Currency.EURS   )      
    XRP_USDT    = dict( value = "XRPUSDT" , base = Currency.XRP    ,   quote =   Currency.USDT   )      
    XTZ_BTC     = dict( value = "XTZBTC" , base = Currency.XTZ    ,   quote =   Currency.BTC    )      
    XTZ_ETH     = dict( value = "XTZETH" , base = Currency.XTZ    ,   quote =   Currency.ETH    )      
    XTZ_USDT    = dict( value = "XTZUSDT" , base = Currency.XTZ    ,   quote =   Currency.USDT   )      
    YFI_BTC     = dict( value = "YFIBTC" , base = Currency.YFI    ,   quote =   Currency.BTC    )      
    YFI_USDT    = dict( value = "YFIUSDT" , base = Currency.YFI    ,   quote =   Currency.USDT   )      
    ZEC_BTC     = dict( value = "ZECBTC" , base = Currency.ZEC    ,   quote =   Currency.BTC    )      
    ZEC_ETH     = dict( value = "ZECETH" , base = Currency.ZEC    ,   quote =   Currency.ETH    )      
    ZEC_EURS    = dict( value = "ZECEURS" , base = Currency.ZEC    ,   quote =   Currency.EURS   )      
    ZEC_USDT    = dict( value = "ZECUSDT" , base = Currency.ZEC    ,   quote =   Currency.USDT   )      


class TimeFrame(_Enum):
    DAYS_1 = 1440
    HOURS_1 = 60
    MINUTES_15 = 15
    MINUTES_5 = 5
    MINUTES_1 = 1

    @staticmethod
    def _format_value(value):
        values = {
            1440: "DAYS_1",
            60: "HOURS_1",
            15: "MINUTES_15",
            5: "MINUTES_5",
            1: "MINUTES_1",
        }
        return values[value]
